### ISSUE TITLE
Workflowfejl

### ISSUE THREAD

**Issue by JanneMarieBarslev** [aarhusstadsarkiv/sam-workflows#75]
Workflow stopper.
Claus forklarer:
Det sker når tif-filen ikke er gemt i standard ”rgb”-mode, mener jeg. Der er nogen, der er kommet til at flytte på en indstilling under scanningen. Prøv at åben billedet i Irfanview, gem kopi som rgb-fil og korrekt bitdybde, og erstat efterfølgende filen i sam.

**Comment by clausjuhl** [comment]
Ny version af programmet skulle gerne være bedre til at håndtere de forskellige tif-konfigurationer. Exe-filen ligger her og skal bare erstatte den forrige exe-fil:

https://github.com/aarhusstadsarkiv/sam-workflows/releases/download/v0.4.1/sam_workflows.exe
