### ISSUE TITLE
Workflow kan ikke håndtere Cr2-filer

### ISSUE THREAD

**Issue by JanneMarieBarslev** [aarhusstadsarkiv/sam-workflows#76]
Har løst problemet ved om konvertere Cr2-filerne til jpg. Er ikke tidligere stødt på Cr2-filer, så det bliver nok ikke et problem vi ofte kommer til at støde på.

**Comment by clausjuhl** [comment]
Jeg har heller aldrig hørt om cr2-filer, så det gør vi nok ikke mere ved. Jeg markerer, at problemet er løst.
